# Generated by Django 4.1 on 2025-01-22 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0017_student_phone"),
        ("middle", "0004_remove_clickjob_dwzzjgdm_clickjob_job"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clickjob",
            name="SID",
        ),
        migrations.AddField(
            model_name="clickjob",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True, help_text="创建时间", null=True, verbose_name="创建时间"
            ),
        ),
        migrations.AddField(
            model_name="clickjob",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student.student",
                verbose_name="学生id",
            ),
        ),
    ]
