# Generated by Django 4.1 on 2025-05-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("middle", "0006_alter_clickjob_satisfied"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "COMPANYID",
                    models.CharField(
                        help_text="企业id", max_length=255, null=True, verbose_name="企业id"
                    ),
                ),
                (
                    "SHTYXYDM",
                    models.CharField(
                        help_text="社会统一信用代码",
                        max_length=255,
                        null=True,
                        verbose_name="社会统一信用代码",
                    ),
                ),
            ],
            options={
                "verbose_name": "社会信用代码-企业id",
                "verbose_name_plural": "社会信用代码-企业id",
                "db_table": "company_code",
            },
        ),
    ]
