# Generated by Django 4.1 on 2024-07-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0009_alter_student_zyfx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="REALNAME",
            field=models.CharField(max_length=100, null=True, verbose_name="学生姓名"),
        ),
    ]
