# Generated by Django 4.1 on 2024-07-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0008_alter_job_dwhymc_alter_job_dwszddm_alter_job_dwxzmc_and_more"),
        ("student", "0010_alter_student_realname"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudentJob",
            new_name="ClickJob",
        ),
        migrations.AlterField(
            model_name="student",
            name="BIRTHDAY",
            field=models.CharField(
                help_text="出生年月", max_length=8, null=True, verbose_name="出生年月"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="DEPARTMENT",
            field=models.CharField(
                help_text="学院", max_length=20, null=True, verbose_name="学院"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="GRADE",
            field=models.CharField(
                help_text="毕业年份", max_length=255, null=True, verbose_name="毕业年份"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="GZZWLBMC",
            field=models.CharField(
                help_text="实习过的工作", max_length=255, null=True, verbose_name="实习过的工作"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="JTDZ",
            field=models.CharField(
                help_text="家庭住址", max_length=255, null=True, verbose_name="家庭住址"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="MAJOR",
            field=models.CharField(
                help_text="专业", max_length=20, null=True, verbose_name="专业"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="REALNAME",
            field=models.CharField(
                help_text="学生姓名", max_length=100, null=True, verbose_name="学生姓名"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="SID",
            field=models.CharField(
                help_text="学号",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="学号",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="XBMC",
            field=models.CharField(
                help_text="性别", max_length=1, null=True, verbose_name="性别"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="XLMC",
            field=models.CharField(
                help_text="学历", max_length=10, null=True, verbose_name="学历"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="XXXSMC",
            field=models.CharField(
                help_text="学习形式", max_length=10, null=True, verbose_name="学习形式"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="ZXWYYZMC",
            field=models.CharField(
                help_text="主修外语", max_length=10, null=True, verbose_name="主修外语"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="ZYFX",
            field=models.CharField(
                help_text="专业方向", max_length=255, null=True, verbose_name="专业方向"
            ),
        ),
    ]
