# Generated by Django 4.1 on 2024-07-23 18:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0011_rename_studentjob_clickjob_alter_student_birthday_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="clickjob",
            table="click_job",
        ),
    ]
