# Generated by Django 4.1 on 2024-11-16 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0015_remove_starjob_dwzzjgdm_remove_starjob_sid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["id"],
                "verbose_name": "学生信息",
                "verbose_name_plural": "学生信息",
            },
        ),
    ]
