# Generated by Django 4.1 on 2024-07-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_remove_user_phone_user_sid_alter_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sid",
            field=models.CharField(max_length=255, verbose_name="学生或企业的唯一标识"),
        ),
    ]
