# Generated by Django 4.1 on 2024-07-28 22:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_clickstudent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClickStudent",
        ),
    ]
