# Generated by Django 4.1 on 2024-07-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.CharField(default="0", max_length=1, verbose_name="用户类型"),
        ),
    ]
