# Generated by Django 4.1 on 2024-11-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_company_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["id"],
                "verbose_name": "公司信息",
                "verbose_name_plural": "公司信息",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.CharField(max_length=255, null=True, verbose_name="单位注册邮箱"),
        ),
        migrations.AddField(
            model_name="company",
            name="unifiedCode",
            field=models.CharField(max_length=255, null=True, verbose_name="统一社会信用代码"),
        ),
    ]
