# Generated by Django 4.1 on 2024-07-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.AddField(
            model_name="user",
            name="sid",
            field=models.CharField(
                default="0", max_length=255, unique=True, verbose_name="学生或企业的唯一标识"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                default="0", max_length=1, verbose_name="用户类型,0学生1企业"
            ),
        ),
    ]
