# Generated by Django 4.1 on 2025-01-16 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("job", "0018_alter_job_options"),
        ("student", "0016_alter_student_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recruit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.IntegerField(default=0)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job.job",
                        verbose_name="职位",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "简历投递表",
                "verbose_name_plural": "简历投递表",
                "db_table": "recruit",
                "ordering": ["id"],
            },
        ),
    ]
