# Generated by Django 4.1 on 2025-01-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruit",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True, help_text="创建时间", null=True, verbose_name="创建时间"
            ),
        ),
    ]
