# Generated by Django 4.1 on 2025-01-09 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("student", "0016_alter_student_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "personalAdvantage",
                    models.CharField(
                        help_text="个人优势", max_length=255, null=True, verbose_name="个人优势"
                    ),
                ),
                (
                    "schoolExperience",
                    models.CharField(
                        help_text="学校经历", max_length=255, null=True, verbose_name="学校经历"
                    ),
                ),
                (
                    "expectedPositions",
                    models.CharField(
                        help_text="期望职位", max_length=255, null=True, verbose_name="期望职位"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                        verbose_name="学生学号",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生简历",
                "verbose_name_plural": "学生简历",
                "db_table": "resume",
                "ordering": ["id"],
            },
        ),
    ]
