# Generated by Django 4.1 on 2024-07-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="name",
            field=models.CharField(max_length=255, null=True, verbose_name="职位名"),
        ),
    ]
