# Generated by Django 4.1 on 2024-07-16 19:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0003_rename_name_job_jobname_job_address_job_companyname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="user",
        ),
    ]
