# Generated by Django 4.1 on 2024-07-16 22:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0004_remove_job_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="industry",
            new_name="DWHYMC",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="address",
            new_name="DWSZDDM",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="companyNature",
            new_name="DWXZMC",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="sid",
            new_name="DWZZJGDM",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="jobName",
            new_name="GZZWLBMC",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="companyName",
            new_name="SJDWMC",
        ),
    ]
