# Generated by Django 4.1 on 2024-07-28 22:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0009_starjob_clickjob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="starjob",
            name="DWZZJGDM",
        ),
        migrations.RemoveField(
            model_name="starjob",
            name="SID",
        ),
        migrations.DeleteModel(
            name="ClickJob",
        ),
        migrations.DeleteModel(
            name="StarJob",
        ),
    ]
