# Generated by Django 4.1 on 2025-03-18 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0021_job_create_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={
                "ordering": ["-create_time"],
                "verbose_name": "职位信息",
                "verbose_name_plural": "职位信息",
            },
        ),
    ]
