# Generated by Django 4.1 on 2025-06-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0023_job_companyid"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="NUM",
            field=models.IntegerField(default=1, help_text="招聘人数", verbose_name="招聘人数"),
        ),
    ]
