# Generated by Django 4.1 on 2024-07-28 22:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("middle", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClickStudent",
        ),
    ]
