# Generated by Django 4.1 on 2025-01-22 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0020_job_company"),
        ("middle", "0003_clickstudent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clickjob",
            name="DWZZJGDM",
        ),
        migrations.AddField(
            model_name="clickjob",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="job.job",
                verbose_name="id",
            ),
        ),
    ]
