# Generated by Django 4.1 on 2025-01-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("middle", "0005_remove_clickjob_sid_clickjob_create_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clickjob",
            name="satisfied",
            field=models.CharField(default=1, max_length=10, verbose_name="是否交互"),
        ),
    ]
