# Generated by Django 4.1 on 2024-07-28 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0015_remove_starjob_dwzzjgdm_remove_starjob_sid_and_more"),
        ("job", "0010_remove_starjob_dwzzjgdm_remove_starjob_sid_and_more"),
        ("middle", "0002_delete_clickstudent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClickStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "satisfied",
                    models.CharField(max_length=10, null=True, verbose_name="是否交互"),
                ),
                (
                    "DWZZJGDM",
                    models.ForeignKey(
                        blank=True,
                        db_column="DWZZJGDM",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job.job",
                        to_field="DWZZJGDM",
                        verbose_name="职位编号",
                    ),
                ),
                (
                    "SID",
                    models.ForeignKey(
                        blank=True,
                        db_column="SID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                        to_field="SID",
                        verbose_name="学生学号",
                    ),
                ),
            ],
            options={
                "verbose_name": "公司浏览学生",
                "verbose_name_plural": "公司浏览学生",
                "db_table": "click_student",
            },
        ),
    ]
