# Generated by Django 4.1 on 2024-07-16 22:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0006_alter_job_dwzzjgdm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="job",
            name="update_at",
        ),
    ]
