# Generated by Django 4.1 on 2024-07-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0007_remove_job_created_at_remove_job_update_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="DWHYMC",
            field=models.CharField(
                help_text="公司所属行业", max_length=255, null=True, verbose_name="公司所属行业"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="DWSZDDM",
            field=models.CharField(
                help_text="工作地址", max_length=255, null=True, verbose_name="工作地址"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="DWXZMC",
            field=models.CharField(
                help_text="公司性质", max_length=255, null=True, verbose_name="公司性质"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="DWZZJGDM",
            field=models.CharField(
                help_text="职位编号",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="职位编号",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="GZZWLBMC",
            field=models.CharField(
                help_text="职位名", max_length=255, null=True, verbose_name="职位名"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="SJDWMC",
            field=models.CharField(
                help_text="公司名", max_length=255, null=True, verbose_name="公司名"
            ),
        ),
    ]
