# Generated by Django 4.1 on 2024-11-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0011_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="time",
            field=models.DateTimeField(
                auto_now_add=True, help_text="发布时间", null=True, verbose_name="发布时间"
            ),
        ),
    ]
