# Generated by Django 4.1 on 2024-11-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0012_work_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="desc",
            field=models.TextField(help_text="职位描述", null=True, verbose_name="职位描述"),
        ),
    ]
