# Generated by Django 4.1 on 2024-11-15 22:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0013_alter_work_desc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="work",
            name="time",
        ),
    ]
