# Generated by Django 4.1 on 2024-11-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0014_remove_work_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="companyName",
            field=models.CharField(
                help_text="单位名称", max_length=255, null=True, verbose_name="单位名称"
            ),
        ),
    ]
