# Generated by Django 4.1 on 2024-11-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0015_alter_work_companyname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="major",
            field=models.TextField(help_text="需求专业", null=True, verbose_name="需求专业"),
        ),
    ]
