# Generated by Django 4.1 on 2024-11-15 23:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0016_alter_work_major"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Work",
        ),
    ]
