# Generated by Django 4.1 on 2025-01-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0018_alter_job_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="degree",
            field=models.CharField(
                help_text="学历", max_length=255, null=True, verbose_name="学历"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="desc",
            field=models.TextField(help_text="职位描述", null=True, verbose_name="职位描述"),
        ),
        migrations.AddField(
            model_name="job",
            name="major",
            field=models.TextField(help_text="需求专业", null=True, verbose_name="需求专业"),
        ),
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.CharField(
                help_text="薪资", max_length=255, null=True, verbose_name="薪资"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="workNature",
            field=models.CharField(
                help_text="工作性质", max_length=255, null=True, verbose_name="工作性质"
            ),
        ),
    ]
