# Generated by Django 4.1 on 2025-01-16 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_alter_company_options_company_email_and_more"),
        ("job", "0019_job_degree_job_desc_job_major_job_salary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.company",
                verbose_name="用户id",
            ),
        ),
    ]
