# Generated by Django 4.1 on 2025-03-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0020_job_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="create_time",
            field=models.DateTimeField(
                help_text="职位发布时间", null=True, verbose_name="职位发布时间"
            ),
        ),
    ]
