# Generated by Django 4.1 on 2024-07-16 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("job", "0002_alter_job_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="name",
            new_name="jobName",
        ),
        migrations.AddField(
            model_name="job",
            name="address",
            field=models.CharField(max_length=255, null=True, verbose_name="工作地址"),
        ),
        migrations.AddField(
            model_name="job",
            name="companyName",
            field=models.CharField(max_length=255, null=True, verbose_name="公司名"),
        ),
        migrations.AddField(
            model_name="job",
            name="companyNature",
            field=models.CharField(max_length=255, null=True, verbose_name="公司性质"),
        ),
        migrations.AddField(
            model_name="job",
            name="industry",
            field=models.CharField(max_length=255, null=True, verbose_name="公司所属行业"),
        ),
        migrations.AddField(
            model_name="job",
            name="sid",
            field=models.CharField(max_length=255, null=True, verbose_name="职位编号"),
        ),
        migrations.AddField(
            model_name="job",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户id",
            ),
        ),
    ]
