# Generated by Django 4.1 on 2024-07-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0005_rename_industry_job_dwhymc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="DWZZJGDM",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="职位编号"
            ),
        ),
    ]
