# Generated by Django 4.1 on 2024-11-16 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0017_delete_work"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={
                "ordering": ["id"],
                "verbose_name": "职位信息",
                "verbose_name_plural": "职位信息",
            },
        ),
    ]
