# Generated by Django 4.1 on 2025-05-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0022_alter_job_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="COMPANYID",
            field=models.CharField(
                help_text="企业id", max_length=255, null=True, verbose_name="企业id"
            ),
        ),
    ]
