# Generated by Django 4.1 on 2025-01-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="skills",
            field=models.CharField(
                help_text="掌握技能", max_length=255, null=True, verbose_name="掌握技能"
            ),
        ),
    ]
