# Generated by Django 4.1 on 2025-03-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0002_resume_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="expectedPositions",
            field=models.TextField(help_text="期望职位", null=True, verbose_name="期望职位"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="personalAdvantage",
            field=models.TextField(help_text="个人优势", null=True, verbose_name="个人优势"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="schoolExperience",
            field=models.TextField(help_text="学校经历", null=True, verbose_name="学校经历"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="skills",
            field=models.TextField(
                help_text="掌握技能", max_length=255, null=True, verbose_name="掌握技能"
            ),
        ),
    ]
