# Generated by Django 4.1 on 2024-07-16 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="name",
            new_name="realName",
        ),
    ]
