# Generated by Django 4.1 on 2024-07-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_rename_name_student_realname"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="address",
            field=models.CharField(max_length=255, null=True, verbose_name="家庭住址"),
        ),
        migrations.AddField(
            model_name="student",
            name="birthday",
            field=models.CharField(max_length=8, null=True, verbose_name="出生年月"),
        ),
        migrations.AddField(
            model_name="student",
            name="degree",
            field=models.CharField(max_length=10, null=True, verbose_name="学历"),
        ),
        migrations.AddField(
            model_name="student",
            name="department",
            field=models.CharField(max_length=20, null=True, verbose_name="学院"),
        ),
        migrations.AddField(
            model_name="student",
            name="foreignLanguage",
            field=models.CharField(max_length=10, null=True, verbose_name="主修外语"),
        ),
        migrations.AddField(
            model_name="student",
            name="graduateYear",
            field=models.CharField(max_length=255, null=True, verbose_name="毕业年份"),
        ),
        migrations.AddField(
            model_name="student",
            name="internedJob",
            field=models.CharField(max_length=255, null=True, verbose_name="实习过的工作"),
        ),
        migrations.AddField(
            model_name="student",
            name="learningForms",
            field=models.CharField(max_length=10, null=True, verbose_name="学习形式"),
        ),
        migrations.AddField(
            model_name="student",
            name="major",
            field=models.CharField(max_length=20, null=True, verbose_name="专业"),
        ),
        migrations.AddField(
            model_name="student",
            name="majorDirection",
            field=models.CharField(max_length=20, null=True, verbose_name="专业方向"),
        ),
        migrations.AddField(
            model_name="student",
            name="sex",
            field=models.CharField(max_length=1, null=True, verbose_name="性别"),
        ),
        migrations.AddField(
            model_name="student",
            name="sid",
            field=models.CharField(max_length=255, null=True, verbose_name="学号"),
        ),
        migrations.AlterField(
            model_name="student",
            name="realName",
            field=models.CharField(max_length=10, null=True, verbose_name="学生姓名"),
        ),
    ]
