# Generated by Django 4.1 on 2024-07-16 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("student", "0003_student_address_student_birthday_student_degree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户id",
            ),
        ),
    ]
