# Generated by Django 4.1 on 2024-07-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0005_rename_user_id_student_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="birthday",
            new_name="BIRTHDAY",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="department",
            new_name="DEPARTMENT",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="graduateYear",
            new_name="GRADE",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="internedJob",
            new_name="GZZWLBMC",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="address",
            new_name="JTDZ",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="major",
            new_name="MAJOR",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="realName",
            new_name="REALNAME",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="sid",
            new_name="SID",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="sex",
            new_name="XBMC",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="learningForms",
            new_name="XXXSMC",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="foreignLanguage",
            new_name="ZXWYYZMC",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="majorDirection",
            new_name="ZYFX",
        ),
        migrations.RemoveField(
            model_name="student",
            name="degree",
        ),
        migrations.RemoveField(
            model_name="student",
            name="user",
        ),
        migrations.AddField(
            model_name="student",
            name="XLMC",
            field=models.CharField(max_length=10, null=True, verbose_name="学历"),
        ),
    ]
