# Generated by Django 4.1 on 2024-07-16 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0006_alter_job_dwzzjgdm"),
        ("student", "0006_rename_birthday_student_birthday_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="SID",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="学号"
            ),
        ),
        migrations.CreateModel(
            name="StudentJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "satisfied",
                    models.CharField(max_length=10, null=True, verbose_name="是否交互"),
                ),
                (
                    "DWZZJGDM",
                    models.ForeignKey(
                        blank=True,
                        db_column="DWZZJGDM",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job.job",
                        to_field="DWZZJGDM",
                        verbose_name="职位编号",
                    ),
                ),
                (
                    "SID",
                    models.ForeignKey(
                        blank=True,
                        db_column="SID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                        to_field="SID",
                        verbose_name="学生学号",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生职位交互表",
                "verbose_name_plural": "学生职位交互表",
                "db_table": "student_job",
            },
        ),
    ]
