# Generated by Django 4.1 on 2024-07-16 22:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0007_alter_student_sid_studentjob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="student",
            name="update_at",
        ),
    ]
