# Generated by Django 4.1 on 2024-07-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0008_remove_student_created_at_remove_student_update_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="ZYFX",
            field=models.CharField(max_length=255, null=True, verbose_name="专业方向"),
        ),
    ]
