# Generated by Django 4.1 on 2025-01-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0016_alter_student_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(
                help_text="手机号码", max_length=255, null=True, verbose_name="手机号码"
            ),
        ),
    ]
