# Generated by Django 4.1 on 2025-02-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0017_student_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="BIRTHDAY",
            field=models.CharField(
                help_text="出生年月", max_length=20, null=True, verbose_name="出生年月"
            ),
        ),
    ]
