# Generated by Django 4.1 on 2025-02-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0018_alter_student_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="MAJOR",
            field=models.CharField(
                help_text="专业", max_length=255, null=True, verbose_name="专业"
            ),
        ),
    ]
