# Generated by Django 4.1 on 2024-07-16 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0004_student_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="user_id",
            new_name="user",
        ),
    ]
