# Generated by Django 4.1 on 2025-05-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_alter_company_options_company_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="COMPANYID",
            field=models.CharField(
                help_text="企业id", max_length=255, null=True, verbose_name="企业id"
            ),
        ),
    ]
