# Generated by Django 4.1 on 2024-11-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "companyName",
                    models.CharField(
                        help_text="单位名称", max_length=255, null=True, verbose_name="单位名称"
                    ),
                ),
                (
                    "workName",
                    models.CharField(
                        help_text="职位名称", max_length=255, null=True, verbose_name="职位名称"
                    ),
                ),
                (
                    "workNum",
                    models.CharField(
                        help_text="职位数", max_length=255, null=True, verbose_name="职位数"
                    ),
                ),
                (
                    "major",
                    models.TextField(help_text="需求专业", null=True, verbose_name="需求专业"),
                ),
                (
                    "salary",
                    models.CharField(
                        help_text="薪资", max_length=255, null=True, verbose_name="薪资"
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        help_text="学历", max_length=255, null=True, verbose_name="学历"
                    ),
                ),
                (
                    "workNature",
                    models.CharField(
                        help_text="工作性质", max_length=255, null=True, verbose_name="工作性质"
                    ),
                ),
                (
                    "desc",
                    models.TextField(help_text="职位描述", null=True, verbose_name="职位描述"),
                ),
            ],
            options={
                "verbose_name": "职位详情",
                "verbose_name_plural": "职位详情",
                "db_table": "work",
            },
        ),
    ]
