# Generated by Django 4.1 on 2024-11-16 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="work",
            options={
                "ordering": ["id"],
                "verbose_name": "职位详情",
                "verbose_name_plural": "职位详情",
            },
        ),
    ]
